version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build: .
    container_name: fastify-backend
    environment:
      DATABASE_URL: "mysql://user:userpassword@db:3306/my_database"
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
